{
 "title": "Monitorización Completa de Sensores",
 "description": "Dashboard combinado con todos los sensores",
 "time": { "from": "2025-04-01T11:26:54.854Z", "to": "2025-05-05T14:30:37.980Z" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Temperatura y Humedad (DHT11)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"my_bucket\") |> range(start: 0) |> filter(fn: (r) => r._measurement == \"humidity\" or r._measurement == \"temperature\")"
    }
   ]
  },
  {
   "title": "Llamas",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"my_bucket\") |> range(start: 0) |> filter(fn: (r) => r._measurement == \"Llama\")"
    }
   ]
  },
  {
   "title": "Pulso y O2 (MAX30102)",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "from(bucket: \"my_bucket\") |> range(start: 0) |> filter(fn: (r) => r._measurement == \"HR\" or r._measurement == \"SpO2\")"
    }
   ]
  },
  {
   "title": "Caídas (MPU6050)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "query": "from(bucket: \"my_bucket\") |> range(start: 0) |> filter(fn: (r) => r._measurement == \"Caida\")"
    }
   ]
  },
  {
   "title": "Gases (MQ135)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "query": "from(bucket: \"my_bucket\") |> range(start: 0) |> filter(fn: (r) => r._measurement == \"Gas\")"
    }
   ]
  },
  {
   "title": "Nivel de Tanque",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "query": "from(bucket: \"my_bucket\") |> range(start: 0) |> filter(fn: (r) => r._measurement == \"WaterLevel\")"
    }
   ]
  }
 ]
}